### ISSUE TITLE
Error signing transactions on Certik (shentu-2.2)

### ISSUE THREAD

**Issue by phantomcrypt** [cosmostation/keystation#21]
**Describe the bug**
Cannot interact with Certik blockchain. All operations, including (re)delegating validator, claiming rewards, etc.

**To Reproduce**
1. Go to https://wallet.cosmostation.io/
2. Select Certik blockchain
3. Connect wallet
4. Do any operation, for instance claiming reward on the Rewards tab
5. Error:
```
Fail to withdraw rewards: signature verification failed; please verify account number (2117), sequence (54) and chain-id (shentu-2.2): unauthorized
```

**Expected behavior**
Transaction should proceed successfully.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: Chromium
 - Version: 94

**Additional context**
It was working before they upgraded mainnet. It appears the `chain-id` must be upgraded to 2.2

**Comment by Booyoun-Kim** [comment]
Thanks for reporting. Fixed it 🙏
