### ISSUE TITLE
ADDING AND DELETING WALLETS? HOW IS IT DONE?

### ISSUE THREAD

**Issue by VIPGYM** [cosmostation/keystation#23]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by VIPGYM** [comment]
HOW DO I DELETE AND ADD WALLETS

**Comment by Booyoun-Kim** [comment]
https://medium.com/cosmostation/introducing-keystation-end-to-end-encrypted-key-manager-for-dapps-built-with-the-cosmos-sdk-37dac753feb5

This article helps you to add and delete your account.
