### ISSUE TITLE
Ulaşamadım varlıklar var

### ISSUE THREAD

**Issue by Mehmetbatmaz** [cosmostation/keystation#32]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Mehmetbatmaz** [comment]
Cosmostation ulaşamadım

**Comment by Mehmetbatmaz** [comment]
Ş
- [ ] []()

**Comment by Booyoun-Kim** [comment]
Spam
