### ISSUE TITLE
Please opening 

### ISSUE THREAD

**Issue by Dmitr33** [cosmostation/keystation#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Dmitr33** [comment]
> 
> 
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
>  - OS: [e.g. iOS]
>  - Browser [e.g. chrome, safari]
>  - Version [e.g. 22]
> 
> **Additional context**
> Add any other context about the problem here.
>

**Comment by Dmitr33** [comment]
> > **Describe the bug**
> > A clear and concise description of what the bug is.
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > 
> > 1. Go to '...'
> > 2. Click on '....'
> > 3. Scroll down to '....'
> > 4. See error
> > 
> > **Expected behavior**
> > A clear and concise description of what you expected to happen.
> > **Screenshots**
> > If applicable, add screenshots to help explain your problem.
> > **Desktop (please complete the following information):**
> > 
> > * OS: [e.g. iOS]
> > * Browser [e.g. chrome, safari]
> > * Version [e.g. 22]
> > 
> > **Additional context**
> > Add any other context about the problem here.

**Comment by Booyoun-Kim** [comment]
Sorry, but I will close this issue.
