### ISSUE TITLE
Нужно убрать эту функцию, иначе редирект не будет работать на странице чекаута.

### ISSUE THREAD

**Issue by Dmitr33** [cosmostation/keystation#5]
Нужно убрать эту функцию, иначе редирект не будет работать на странице чекаута.

_Originally posted by @kolucciy in https://github.com/liqpay/plugin-magento/pull/27#discussion_r435222461_

**Comment by Amazzon** [comment]
> Нужно убрать эту функцию, иначе редирект не будет работать на странице чекаута.
> 
> _Originally posted by @kolucciy in [liqpay/plugin-magento#27 (comment)](https://github.com/liqpay/plugin-magento/pull/27#discussion_r435222461)_

Читай все комменты, перед тем как писать. 
Все работает прекрасно если ты переключится на ветку 2.3!!!
